// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SemptomAnalizApp.Data;

#nullable disable

namespace SemptomAnalizApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329225311_ProductionGradeRebuild")]
    partial class ProductionGradeRebuild
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.AnalizOturumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EkNotlar")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SemptomImzasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("SemptomImzasi");

                    b.ToTable("AnalizOturumlari", (string)null);
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.AnalizSemptomu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalizOturumuId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SemptomKatalogId")
                        .HasColumnType("integer");

                    b.Property<int>("Siddet")
                        .HasColumnType("integer");

                    b.Property<int>("SureGun")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalizOturumuId");

                    b.HasIndex("SemptomKatalogId");

                    b.ToTable("AnalizSemptomlari", (string)null);
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.AnalizSonucu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AciliyetSeviyesi")
                        .HasColumnType("integer");

                    b.Property<int>("AciliyetSkoru")
                        .HasColumnType("integer");

                    b.Property<int>("AnalizOturumuId")
                        .HasColumnType("integer");

                    b.Property<int>("BmiKategori")
                        .HasColumnType("integer");

                    b.Property<int?>("EnYakinTekrarGunOncesi")
                        .HasColumnType("integer");

                    b.Property<string>("GenelYorum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GunlukOnerilerJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("HesaplananBmi")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("NedenAciklamasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OnerilenBolum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TekrarSkoru")
                        .HasColumnType("integer");

                    b.Property<string>("UyariGostergeleriJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalizOturumuId")
                        .IsUnique();

                    b.ToTable("AnalizSonuclari", (string)null);
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.Hastalik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AkutMu")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ErkekKatsayi")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("KadinKatsayi")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<int?>("MaxYas")
                        .HasColumnType("integer");

                    b.Property<int?>("MinYas")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OnerilenBolum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Prevalans")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Hastaliklar", (string)null);
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.HastalikSemptom", b =>
                {
                    b.Property<int>("HastalikId")
                        .HasColumnType("integer");

                    b.Property<int>("SemptomId")
                        .HasColumnType("integer");

                    b.Property<int>("Agirlik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.HasKey("HastalikId", "SemptomId");

                    b.HasIndex("SemptomId");

                    b.ToTable("HastalikSemptomlar", (string)null);
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.Kullanici", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.OlasiDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AnalizSonucuId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HastalikId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SkorYuzdesi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalizSonucuId");

                    b.HasIndex("HastalikId");

                    b.ToTable("OlasiDurumlar", (string)null);
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.SaglikProfili", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Boy")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Kilo")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<string>("KronikHastaliklar")
                        .HasColumnType("text");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notlar")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Yas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId")
                        .IsUnique();

                    b.ToTable("SaglikProfilleri", (string)null);
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.Semptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("KritikMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Semptomlar", (string)null);
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.SemptomKatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IkonKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kategori")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SemptomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SemptomId");

                    b.ToTable("SemptomKatalog", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SemptomAnalizApp.Core.Entities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SemptomAnalizApp.Core.Entities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SemptomAnalizApp.Core.Entities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SemptomAnalizApp.Core.Entities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.AnalizOturumu", b =>
                {
                    b.HasOne("SemptomAnalizApp.Core.Entities.Kullanici", "Kullanici")
                        .WithMany("AnalizOturumlari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.AnalizSemptomu", b =>
                {
                    b.HasOne("SemptomAnalizApp.Core.Entities.AnalizOturumu", "AnalizOturumu")
                        .WithMany("AnalizSemptomlari")
                        .HasForeignKey("AnalizOturumuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SemptomAnalizApp.Core.Entities.SemptomKatalog", "SemptomKatalog")
                        .WithMany("AnalizSemptomlari")
                        .HasForeignKey("SemptomKatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalizOturumu");

                    b.Navigation("SemptomKatalog");
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.AnalizSonucu", b =>
                {
                    b.HasOne("SemptomAnalizApp.Core.Entities.AnalizOturumu", "AnalizOturumu")
                        .WithOne("AnalizSonucu")
                        .HasForeignKey("SemptomAnalizApp.Core.Entities.AnalizSonucu", "AnalizOturumuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalizOturumu");
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.HastalikSemptom", b =>
                {
                    b.HasOne("SemptomAnalizApp.Core.Entities.Hastalik", "Hastalik")
                        .WithMany("HastalikSemptomlari")
                        .HasForeignKey("HastalikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SemptomAnalizApp.Core.Entities.Semptom", "Semptom")
                        .WithMany("HastalikSemptomlari")
                        .HasForeignKey("SemptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hastalik");

                    b.Navigation("Semptom");
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.OlasiDurum", b =>
                {
                    b.HasOne("SemptomAnalizApp.Core.Entities.AnalizSonucu", "AnalizSonucu")
                        .WithMany("OlasiDurumlar")
                        .HasForeignKey("AnalizSonucuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SemptomAnalizApp.Core.Entities.Hastalik", "Hastalik")
                        .WithMany()
                        .HasForeignKey("HastalikId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AnalizSonucu");

                    b.Navigation("Hastalik");
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.SaglikProfili", b =>
                {
                    b.HasOne("SemptomAnalizApp.Core.Entities.Kullanici", "Kullanici")
                        .WithOne("SaglikProfili")
                        .HasForeignKey("SemptomAnalizApp.Core.Entities.SaglikProfili", "KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.SemptomKatalog", b =>
                {
                    b.HasOne("SemptomAnalizApp.Core.Entities.Semptom", "Semptom")
                        .WithMany()
                        .HasForeignKey("SemptomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Semptom");
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.AnalizOturumu", b =>
                {
                    b.Navigation("AnalizSemptomlari");

                    b.Navigation("AnalizSonucu");
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.AnalizSonucu", b =>
                {
                    b.Navigation("OlasiDurumlar");
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.Hastalik", b =>
                {
                    b.Navigation("HastalikSemptomlari");
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.Kullanici", b =>
                {
                    b.Navigation("AnalizOturumlari");

                    b.Navigation("SaglikProfili");
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.Semptom", b =>
                {
                    b.Navigation("HastalikSemptomlari");
                });

            modelBuilder.Entity("SemptomAnalizApp.Core.Entities.SemptomKatalog", b =>
                {
                    b.Navigation("AnalizSemptomlari");
                });
#pragma warning restore 612, 618
        }
    }
}
